name: Release xui
on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
          
  linux-build:
    name: Build xui for Linux (amd64 and arm64)
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip unzip dos2unix
      
      - name: Build and package
        run: |
          # Make release script executable
          chmod +x release.sh
          
          # Run the release script
          ./release.sh
          
          # Verify the packages
          ls -la release/
          
      - name: Upload amd64 package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: release/xui-linux-amd64.tar.gz
          asset_name: xui-linux-amd64.tar.gz
          asset_content_type: application/gzip
          
      - name: Upload amd64 zip package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: release/xui-linux-amd64.zip
          asset_name: xui-linux-amd64.zip
          asset_content_type: application/zip
          
      - name: Upload arm64 package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: release/xui-linux-arm64.tar.gz
          asset_name: xui-linux-arm64.tar.gz
          asset_content_type: application/gzip
          
      - name: Upload arm64 zip package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: release/xui-linux-arm64.zip
          asset_name: xui-linux-arm64.zip
          asset_content_type: application/zip